//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEngine.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class customexam
    {
        public int examid { get; set; }
        public string examnadfme { get; set; }
        public Nullable<int> catid { get; set; }
        public string syllabus { get; set; }
        public string prerequisites { get; set; }
        public string partner { get; set; }
        public Nullable<decimal> price { get; set; }
        public string ibillproductid { get; set; }
        public string psproductid { get; set; }
        public string comments { get; set; }
        public string logo { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> questioncount { get; set; }
        public string offline { get; set; }
        public string randomtest { get; set; }
        public string pagename { get; set; }
        public string usepage { get; set; }
        public string printname { get; set; }
        public string resultpage { get; set; }
        public string transcriptpage { get; set; }
        public string showcorporate { get; set; }
        public string courseware { get; set; }
        public string coursepath { get; set; }
        public string productId2CO { get; set; }
        public Nullable<int> priority { get; set; }
        public string positioning { get; set; }
        public string directions { get; set; }
        public string haspassage { get; set; }
        public Nullable<int> passagenum { get; set; }
        public Nullable<int> positive { get; set; }
        public string odeskexam { get; set; }
        public string recertification { get; set; }
        public string isbeta { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public Nullable<int> passingmarks { get; set; }
        public string examlanguage { get; set; }
        public Nullable<int> masterexamid { get; set; }
        public Nullable<int> refid { get; set; }
        public Nullable<int> refid1 { get; set; }
        public Nullable<int> foreignexamid { get; set; }
        public string elmlxmlname { get; set; }
        public Nullable<int> isfn { get; set; }
        public string examenablepartners { get; set; }
        public Nullable<bool> commoncodelive { get; set; }
        public Nullable<bool> isCronbach { get; set; }
        public string JobTitleID { get; set; }
        public string masterXmlfile { get; set; }
        public string SurCatPageUrl { get; set; }
        public Nullable<int> addedby { get; set; }
        public Nullable<bool> isfreezed { get; set; }
        public Nullable<bool> isfrree { get; set; }
        public Nullable<int> addedbytest { get; set; }
        public Nullable<bool> flagged { get; set; }
        public string flagerror { get; set; }
        public Nullable<bool> flagged1 { get; set; }
        public Nullable<bool> showendbtn { get; set; }
        public string idset { get; set; }
        public Nullable<bool> isidset { get; set; }
        public Nullable<int> languagetype { get; set; }
        public Nullable<int> languagetype1 { get; set; }
    }
}
