//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEngine.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomSection
    {
        public int Id { get; set; }
        public string sectionname { get; set; }
        public string sectiondesc { get; set; }
        public Nullable<int> examid { get; set; }
        public Nullable<int> sectionid { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> refid { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> refid1 { get; set; }
        public Nullable<int> subtype { get; set; }
    }
}
