//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEngine.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int Id { get; set; }
        public string LogMessage { get; set; }
        public string LogLineNumber { get; set; }
        public string LogTime { get; set; }
        public string StackTime { get; set; }
        public string LogUrl { get; set; }
    }
}
